### ISSUE TITLE
Drag the toolbar around and other improvements

### ISSUE THREAD

**Issue by jivvy** [geovens/gInk#32]
Love the program. You beat out Epic Pen in not just UI but design and memory usage.
I hate to bunch together a lot of things, I know it makes it difficult to mark resolved, but I think adding a dozen new issues would be just as bad.
Currently on Windows 10 Version 1803 (OS Build 17134.829)

**I'll number them so you can address them if need be:**

1. Currently dashboard is only drawn on main screen. Much cleaner in most use cases to be able to select pens on another monitor without cluttering screen that is being shown/drawn on. Even nicer to be able to simply drag the dashboard around.

2. Hotkey to toggle cursor and previously used brush. Hotkeys for clearing, erasing, increasing/decreasing brush size also appreciated. 

3. Cannot select 'Change Brush Size' button when cursor mode is selected.

4. Text.

**Bugs:**

5. Drawings seem to be updated after pen stroke ends. Random artifacts like these occur:
![image](https://user-images.githubusercontent.com/24281896/60070455-5be1b180-96dc-11e9-9e7d-de9822486bdd.png)

6. This one is a bit weird: I _believe_ this is gInk causing this because it goes away when gInk is closed. When the Windows taskbar is on the top of the screen, a horizontal black line appears maybe 5-10 pixels high between the taskbar and an open, maximized window:
![image](https://user-images.githubusercontent.com/24281896/60070945-145c2500-96de-11e9-8cd4-5b5fb9b6402e.png)
It may be hard to see because of my black taskbar, I haven't activated Windows yet, so unfortunately I cannot change the color. However, you should be able to see the bottom part of the system date being cut off.

**Functionally speaking, very minor:** 

7. Dashboard seems to open and close at 60 hz even on a 144 hz monitor.
Enable the 'Pen tip' canvas cursor by default.

**Uncertain of feasibility:**

8. Drawing over fullscreen apps.

**Comment by Jivvy** [comment]
#1 is definitely the biggest point, and is what caused me to do that bit of bug testing. Being able to move the dashboard will be immensely helpful. Hate to make more work if you're busy though.

**Comment by geovens** [comment]
Hi Jivvy. Thank you for all the suggestions. I will look into at least Number 1 (dragging the dashboard) and try to implement it if it's not too hard.
Could you explain more about Number 3?

**Comment by Jivvy** [comment]
Here, I made a gif. The cursor is a bit off in part of the recording, but it's not like that in use. https://i.imgur.com/oyWCBF7.gif

**Comment by geovens** [comment]
Ok, I see what you meant now. It doesn't work for me either.

**Comment by geovens** [comment]
Hi Jivvy. I made quite a few changes. If you are willing to, you may help checking how the new version (0.6.0) works.  
1. Dragging toolbar has been implemented. There is still a known problem when dragging between multiple screens of unmatched DPI settings, but no plan to fix it.  
2. Hotkeys are in the Options Window now.  
3. Not fixed yet. May investigate later.  
4. No plan. Too hard.  
5. I think I have fixed this.  
6. This is really weird. Do you use multiple screen? Were your DPI setting at 100%?  
7. No plan to fix this. Actually, with the new version (0.6.0) the sliding of the toolbar may be even slower because more drawing is done during every frame.  
8. Not tested yet. May or may not investigate later.

**Comment by Jivvy** [comment]
All the changes are fantastic. I'm not seeing any modifications to the drawings, Panning and moving the toolbar work nicely. Re-work of the options UI makes it simpler and more elegant. I couldn't think of any problems, nor find any bugs. Well done!

**Comment by reactofx** [comment]
Hi Jivvy, I see you are able to move the the tool-bar around, but I'm not. Could you please tell me where to grab the tool-bar in order to move it around, I don't see a specific point to grab it.

**Comment by geovens** [comment]
first you need to enable the option in settings. then you can drag on any point of the toolbar.

**Comment by reactofx** [comment]
Hi geovens,

I have "Allow dragging toolbar" on, but I cannot move the toolbar around, not when it is opened and not when it is folded.

Suggestion for improvement:
When the option pen-tip instead of arrow is on, and one activates the eraser, it is almost not visible, certainly not on a black background

**Comment by RichSteele** [comment]
I, too, haven't been able to drag the toolbar around. I do have the option selected but no luck.

**Comment by RaphanW** [comment]
For those who can't drag, make sure gInk is closed in the taskbar and re-check config.ini. 

My config file reset to 'Allow_Dragging_Toolbar = False' until I changed it to 'Allow_Dragging_Toolbar = True' with all instance of gInk closed

**Comment by RaphanW** [comment]
For those who can't drag, make sure gInk is closed in the taskbar and re-check config.ini.

My config file reset to 'Allow_Dragging_Toolbar = False' until I changed it to 'Allow_Dragging_Toolbar = True' with all instances of gInk closed
