### ISSUE TITLE
Toolbar completely not available

### ISSUE THREAD

**Issue by iksub** [geovens/gInk#67]
Hello,
I just downloaded 1.0.8 version. I get the arrow but I cannot get the toolbar. It is not visible. Through a hotkey either. What should I do?

**Comment by iksub** [comment]
I figured out that the issue is not with the toolbar per se, but with the fact that the multi-monitor seems not supported any longer. I used v1.0.3 and I was able to drag the toolbar to the connected monitor from my laptop monitor. Now, once I drag it it completely disappears on the second monitor.
Please bring back the multi-monitor support.

**Comment by geovens** [comment]
hi, could you tell me more detail about your multiple screen configuration? like, how many screens, what's the resolution for each of them, what's the dpi setting for each of them, etc? there were very few changes from 1.0.3 to 1.0.8 and so it's a surprise that would happen

**Comment by iksub** [comment]
Sorry, not a technical person to give you such details. It is just 2 screens, one -laptop, the other is a 4k monitor connected through hdmi.

**Comment by geovens** [comment]
This is probably due to a known issue under multiple displays of unmatched DPI settings. There is currently no fix for it, but I made a workaround and will release it in v1.0.9. You could download the attached preview of v1.0.9, and do the following before running it to see whether this could fix the problem for you:

right-click gInk.exe, Properties, Compatibility, Change high DPI settings, Enable override high DPI scaling behavior scaling performed by: Application. 

[gInk_v1.0.9rc1.zip](https://github.com/geovens/gInk/files/4424878/gInk_v1.0.9rc1.zip)
